### ISSUE TITLE
nn.BatchNorm2d cannot process input with 4 dims.

### ISSUE THREAD

**Issue by xmengli** [adambielski/pytorch-gconv-experiments#1]
When I test the file resnet.py, I  encountered the problems. It seems the nn.BatchNorm2d cannot process 5 dims input. 

```
def test():
    net = ResNet101()
    y = net(Variable(torch.randn(1,3,32,32)))
    print(y.size())
```

```
Traceback (most recent call last):
  File "resnet.py", line 124, in <module>
    test()
  File "resnet.py", line 121, in test
    y = net(Variable(torch.randn(1,3,32,32)))
  File "/home/xmli/anaconda2/envs/python2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "resnet.py", line 90, in forward
    out = F.relu(self.bn1(self.conv1(x)))
  File "/home/xmli/anaconda2/envs/python2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xmli/anaconda2/envs/python2/lib/python2.7/site-packages/torch/nn/modules/batchnorm.py", line 45, in forward
    self._check_input_dim(input)
  File "/home/xmli/anaconda2/envs/python2/lib/python2.7/site-packages/torch/nn/modules/batchnorm.py", line 193, in _check_input_dim
    .format(input.dim()))
ValueError: expected 4D input (got 5D input)
```

**Comment by xmengli** [comment]
Hi, I changed all  `nn.BatchNorm2d` to  `nn.BatchNorm3d` in the resnet.py file and it works now. 
Run cifar.py at epoch 120, it achieves 94.00 on the test dataset. Maybe it is the correct solution.

**Comment by adambielski** [comment]
It seems to have worked with pytorch 0.2.0 when I was writing that, something must have changed with newer versions of PyTorch. Well spotted.

**Comment by MahsaSeifikar** [comment]
> Hi, I changed all `nn.BatchNorm2d` to `nn.BatchNorm3d` in the resnet.py file and it works now.
> Run cifar.py at epoch 120, it achieves 94.00 on the test dataset. Maybe it is the correct solution.

Could you explain the reason?

**Comment by vincent341** [comment]
How about changing the shape of feature maps by "x = x.view(xs[0], xs[1] * xs[2], xs[3], xs[4])", then feeding it to BatchNorm2d, where xs is the shape of x?

**Comment by meiji163** [comment]
@MahsaSeifikar the output of P4ConvZ2 has dimension 8 x 32 x 32, (where 32 x 32 is the original image size). The 8 dimensions correspond to the elements of the group (rotations and reflections of a square)

**Comment by chenkxin** [comment]
> Hi, I changed all `nn.BatchNorm2d` to `nn.BatchNorm3d` in the resnet.py file and it works now. Run cifar.py at epoch 120, it achieves 94.00 on the test dataset. Maybe it is the correct solution.

Thank you for your solution. It works for me.
